<?php
/**
 * InvestigationLocatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvestigationLocatorTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a locator string for filtering Investigation entities.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvestigationLocatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvestigationLocator"
     */
    public function testInvestigationLocator()
    {
    }

    /**
     * Test attribute "affected_project"
     */
    public function testPropertyAffectedProject()
    {
    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {
    }

    /**
     * Test attribute "assignment_project"
     */
    public function testPropertyAssignmentProject()
    {
    }

    /**
     * Test attribute "build_type"
     */
    public function testPropertyBuildType()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "lookup_limit"
     */
    public function testPropertyLookupLimit()
    {
    }

    /**
     * Test attribute "problem"
     */
    public function testPropertyProblem()
    {
    }

    /**
     * Test attribute "reporter"
     */
    public function testPropertyReporter()
    {
    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {
    }

    /**
     * Test attribute "since_date"
     */
    public function testPropertySinceDate()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
