<?php
/**
 * TestOccurrenceLocatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AceViral\TeamCity;

/**
 * TestOccurrenceLocatorTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a locator string for filtering TestOccurrence entities.
 * @package     AceViral\TeamCity
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TestOccurrenceLocatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TestOccurrenceLocator"
     */
    public function testTestOccurrenceLocator()
    {
    }

    /**
     * Test attribute "affected_project"
     */
    public function testPropertyAffectedProject()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "build"
     */
    public function testPropertyBuild()
    {
    }

    /**
     * Test attribute "build_type"
     */
    public function testPropertyBuildType()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "currently_failing"
     */
    public function testPropertyCurrentlyFailing()
    {
    }

    /**
     * Test attribute "currently_investigated"
     */
    public function testPropertyCurrentlyInvestigated()
    {
    }

    /**
     * Test attribute "currently_muted"
     */
    public function testPropertyCurrentlyMuted()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ignored"
     */
    public function testPropertyIgnored()
    {
    }

    /**
     * Test attribute "include_personal"
     */
    public function testPropertyIncludePersonal()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "lookup_limit"
     */
    public function testPropertyLookupLimit()
    {
    }

    /**
     * Test attribute "muted"
     */
    public function testPropertyMuted()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "new_failure"
     */
    public function testPropertyNewFailure()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }
}
