<?php
/**
 * AgentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AceViral\TeamCity;

use \AceViral\TeamCity\Configuration;
use \AceViral\TeamCity\ApiException;
use \AceViral\TeamCity\ObjectSerializer;

/**
 * AgentApiTest Class Doc Comment
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAgent
     *
     * Delete an inactive agent..
     *
     */
    public function testDeleteAgent()
    {
    }

    /**
     * Test case for getAgent
     *
     * Get agent matching the locator..
     *
     */
    public function testGetAgent()
    {
    }

    /**
     * Test case for getAgentField
     *
     * Get a field of the matching agent..
     *
     */
    public function testGetAgentField()
    {
    }

    /**
     * Test case for getAgentPool
     *
     * Get the agent pool of the matching agent..
     *
     */
    public function testGetAgentPool()
    {
    }

    /**
     * Test case for getAllAgents
     *
     * Get all known agents..
     *
     */
    public function testGetAllAgents()
    {
    }

    /**
     * Test case for getAuthorizedInfo
     *
     * Get the authorization info of the matching agent..
     *
     */
    public function testGetAuthorizedInfo()
    {
    }

    /**
     * Test case for getBuildConfigurationRunPolicy
     *
     * Get the build configuration run policy of the matching agent..
     *
     */
    public function testGetBuildConfigurationRunPolicy()
    {
    }

    /**
     * Test case for getCompatibleBuildTypes
     *
     * Get build types compatible with the matching agent..
     *
     */
    public function testGetCompatibleBuildTypes()
    {
    }

    /**
     * Test case for getEnabledInfo
     *
     * Check if the matching agent is enabled..
     *
     */
    public function testGetEnabledInfo()
    {
    }

    /**
     * Test case for getIncompatibleBuildTypes
     *
     * Get build types incompatible with the matching agent..
     *
     */
    public function testGetIncompatibleBuildTypes()
    {
    }

    /**
     * Test case for setAgentField
     *
     * Update a field of the matching agent..
     *
     */
    public function testSetAgentField()
    {
    }

    /**
     * Test case for setAgentPool
     *
     * Assign the matching agent to the specified agent pool..
     *
     */
    public function testSetAgentPool()
    {
    }

    /**
     * Test case for setAuthorizedInfo
     *
     * Update the authorization info of the matching agent..
     *
     */
    public function testSetAuthorizedInfo()
    {
    }

    /**
     * Test case for setBuildConfigurationRunPolicy
     *
     * Update build configuration run policy of agent matching locator..
     *
     */
    public function testSetBuildConfigurationRunPolicy()
    {
    }

    /**
     * Test case for setEnabledInfo
     *
     * Update the enablement status of the matching agent..
     *
     */
    public function testSetEnabledInfo()
    {
    }
}
