<?php
/**
 * BuildTypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BuildTypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuildTypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addAgentRequirementToBuildType
     *
     * Add an agent requirement to the matching build configuration..
     *
     */
    public function testAddAgentRequirementToBuildType()
    {
    }

    /**
     * Test case for addArtifactDependencyToBuildType
     *
     * Add an artifact dependency to the matching build configuration..
     *
     */
    public function testAddArtifactDependencyToBuildType()
    {
    }

    /**
     * Test case for addBuildFeatureToBuildType
     *
     * Add build feature to the matching build configuration..
     *
     */
    public function testAddBuildFeatureToBuildType()
    {
    }

    /**
     * Test case for addBuildStepToBuildType
     *
     * Add a build step to the matching build configuration..
     *
     */
    public function testAddBuildStepToBuildType()
    {
    }

    /**
     * Test case for addBuildTemplate
     *
     * Add a build template to the matching build configuration..
     *
     */
    public function testAddBuildTemplate()
    {
    }

    /**
     * Test case for addParameterToBuildFeature
     *
     * Update build feature parameter for the matching build configuration..
     *
     */
    public function testAddParameterToBuildFeature()
    {
    }

    /**
     * Test case for addParameterToBuildStep
     *
     * Add a parameter to a build step of the matching build configuration..
     *
     */
    public function testAddParameterToBuildStep()
    {
    }

    /**
     * Test case for addSnapshotDependencyToBuildType
     *
     * Add a snapshot dependency to the matching build configuration..
     *
     */
    public function testAddSnapshotDependencyToBuildType()
    {
    }

    /**
     * Test case for addTriggerToBuildType
     *
     * Add a trigger to the matching build configuration..
     *
     */
    public function testAddTriggerToBuildType()
    {
    }

    /**
     * Test case for addVcsRootToBuildType
     *
     * Add a VCS root to the matching build..
     *
     */
    public function testAddVcsRootToBuildType()
    {
    }

    /**
     * Test case for createBuildParameterOfBuildType
     *
     * Create a build parameter..
     *
     */
    public function testCreateBuildParameterOfBuildType()
    {
    }

    /**
     * Test case for createBuildType
     *
     * Create a new build configuration..
     *
     */
    public function testCreateBuildType()
    {
    }

    /**
     * Test case for deleteAgentRequirement
     *
     * Remove an agent requirement of the matching build configuration..
     *
     */
    public function testDeleteAgentRequirement()
    {
    }

    /**
     * Test case for deleteArtifactDependency
     *
     * Remove an artifact dependency from the matching build configuration..
     *
     */
    public function testDeleteArtifactDependency()
    {
    }

    /**
     * Test case for deleteBuildParameterOfBuildType
     *
     * Delete build parameter..
     *
     */
    public function testDeleteBuildParameterOfBuildType()
    {
    }

    /**
     * Test case for deleteBuildParametersOfBuildType
     *
     * Delete all build parameters..
     *
     */
    public function testDeleteBuildParametersOfBuildType()
    {
    }

    /**
     * Test case for deleteBuildStep
     *
     * Delete a build step of the matching build configuration..
     *
     */
    public function testDeleteBuildStep()
    {
    }

    /**
     * Test case for deleteBuildStepParameters
     *
     * Update a parameter of a build step of the matching build configuration..
     *
     */
    public function testDeleteBuildStepParameters()
    {
    }

    /**
     * Test case for deleteBuildType
     *
     * Delete build configuration matching the locator..
     *
     */
    public function testDeleteBuildType()
    {
    }

    /**
     * Test case for deleteFeatureOfBuildType
     *
     * Remove a build feature of the matching build configuration..
     *
     */
    public function testDeleteFeatureOfBuildType()
    {
    }

    /**
     * Test case for deleteSnapshotDependency
     *
     * Delete a snapshot dependency of the matching build configuration..
     *
     */
    public function testDeleteSnapshotDependency()
    {
    }

    /**
     * Test case for deleteTrigger
     *
     * Delete a trigger of the matching build configuration..
     *
     */
    public function testDeleteTrigger()
    {
    }

    /**
     * Test case for deleteVcsRootOfBuildType
     *
     * Remove a VCS root of the matching build configuration..
     *
     */
    public function testDeleteVcsRootOfBuildType()
    {
    }

    /**
     * Test case for downloadFileOfBuildType
     *
     * Download specific file..
     *
     */
    public function testDownloadFileOfBuildType()
    {
    }

    /**
     * Test case for getAgentRequirement
     *
     * Get an agent requirement of the matching build configuration..
     *
     */
    public function testGetAgentRequirement()
    {
    }

    /**
     * Test case for getAgentRequirementParameter
     *
     * Get a setting of an agent requirement of the matching build configuration..
     *
     */
    public function testGetAgentRequirementParameter()
    {
    }

    /**
     * Test case for getAliases
     *
     * Get external IDs of the matching build configuration..
     *
     */
    public function testGetAliases()
    {
    }

    /**
     * Test case for getAllAgentRequirements
     *
     * Get all agent requirements of the matching build configuration..
     *
     */
    public function testGetAllAgentRequirements()
    {
    }

    /**
     * Test case for getAllArtifactDependencies
     *
     * Get all artifact dependencies of the matching build configuration..
     *
     */
    public function testGetAllArtifactDependencies()
    {
    }

    /**
     * Test case for getAllBranchesOfBuildType
     *
     * Get all branches of the matching build configuration..
     *
     */
    public function testGetAllBranchesOfBuildType()
    {
    }

    /**
     * Test case for getAllBuildFeatureParameters
     *
     * Get all parameters of a build feature of the matching build configuration..
     *
     */
    public function testGetAllBuildFeatureParameters()
    {
    }

    /**
     * Test case for getAllBuildFeatures
     *
     * Get all build features of the matching build configuration..
     *
     */
    public function testGetAllBuildFeatures()
    {
    }

    /**
     * Test case for getAllBuildStepParameters
     *
     * Get all parameters of a build step of the matching build configuration..
     *
     */
    public function testGetAllBuildStepParameters()
    {
    }

    /**
     * Test case for getAllBuildSteps
     *
     * Get all build steps of the matching build configuration..
     *
     */
    public function testGetAllBuildSteps()
    {
    }

    /**
     * Test case for getAllBuildTemplates
     *
     * Get all build templates of the matching build configuration..
     *
     */
    public function testGetAllBuildTemplates()
    {
    }

    /**
     * Test case for getAllBuildTypes
     *
     * Get all build configurations..
     *
     */
    public function testGetAllBuildTypes()
    {
    }

    /**
     * Test case for getAllInvestigationsOfBuildType
     *
     * Get all investigations of the matching build configuration..
     *
     */
    public function testGetAllInvestigationsOfBuildType()
    {
    }

    /**
     * Test case for getAllSnapshotDependencies
     *
     * Get all snapshot dependencies of the matching build configuration..
     *
     */
    public function testGetAllSnapshotDependencies()
    {
    }

    /**
     * Test case for getAllTriggers
     *
     * Get all triggers of the matching build configuration..
     *
     */
    public function testGetAllTriggers()
    {
    }

    /**
     * Test case for getAllVcsRootsOfBuildType
     *
     * Get all VCS roots of the matching build configuration..
     *
     */
    public function testGetAllVcsRootsOfBuildType()
    {
    }

    /**
     * Test case for getArtifactDependency
     *
     * Get an artifact dependency of the matching build configuration..
     *
     */
    public function testGetArtifactDependency()
    {
    }

    /**
     * Test case for getArtifactDependencyParameter
     *
     * Get a parameter of an artifact dependency of the matching build configuration..
     *
     */
    public function testGetArtifactDependencyParameter()
    {
    }

    /**
     * Test case for getBuildFeature
     *
     * Get a build feature of the matching build configuration..
     *
     */
    public function testGetBuildFeature()
    {
    }

    /**
     * Test case for getBuildFeatureParameter
     *
     * Get a parameter of a build feature of the matching build configuration..
     *
     */
    public function testGetBuildFeatureParameter()
    {
    }

    /**
     * Test case for getBuildFeatureSetting
     *
     * Get the setting of a build feature of the matching build configuration..
     *
     */
    public function testGetBuildFeatureSetting()
    {
    }

    /**
     * Test case for getBuildParameterOfBuildType
     *
     * Get build parameter..
     *
     */
    public function testGetBuildParameterOfBuildType()
    {
    }

    /**
     * Test case for getBuildParameterSpecificationOfBuildType
     *
     * Get build parameter specification..
     *
     */
    public function testGetBuildParameterSpecificationOfBuildType()
    {
    }

    /**
     * Test case for getBuildParameterTypeOfBuildType
     *
     * Get type of build parameter..
     *
     */
    public function testGetBuildParameterTypeOfBuildType()
    {
    }

    /**
     * Test case for getBuildParameterValueOfBuildType
     *
     * Get value of build parameter..
     *
     */
    public function testGetBuildParameterValueOfBuildType()
    {
    }

    /**
     * Test case for getBuildParametersOfBuildType
     *
     * Get build parameters..
     *
     */
    public function testGetBuildParametersOfBuildType()
    {
    }

    /**
     * Test case for getBuildStep
     *
     * Get a build step of the matching build configuration..
     *
     */
    public function testGetBuildStep()
    {
    }

    /**
     * Test case for getBuildStepParameter
     *
     * Get a parameter of a build step of the matching build configuration..
     *
     */
    public function testGetBuildStepParameter()
    {
    }

    /**
     * Test case for getBuildStepSetting
     *
     * Get the setting of a build step of the matching build configuration..
     *
     */
    public function testGetBuildStepSetting()
    {
    }

    /**
     * Test case for getBuildTemplate
     *
     * Get a template of the matching build configuration..
     *
     */
    public function testGetBuildTemplate()
    {
    }

    /**
     * Test case for getBuildType
     *
     * Get build configuration matching the locator..
     *
     */
    public function testGetBuildType()
    {
    }

    /**
     * Test case for getBuildTypeBuildTags
     *
     * Get tags of builds of the matching build configuration..
     *
     */
    public function testGetBuildTypeBuildTags()
    {
    }

    /**
     * Test case for getBuildTypeBuilds
     *
     * Get builds of the matching build configuration..
     *
     */
    public function testGetBuildTypeBuilds()
    {
    }

    /**
     * Test case for getBuildTypeField
     *
     * Get a field of the matching build configuration..
     *
     */
    public function testGetBuildTypeField()
    {
    }

    /**
     * Test case for getBuildTypeSettingsFile
     *
     * Get the settings file of the matching build configuration..
     *
     */
    public function testGetBuildTypeSettingsFile()
    {
    }

    /**
     * Test case for getFileMetadataOfBuildType
     *
     * Get metadata of specific file..
     *
     */
    public function testGetFileMetadataOfBuildType()
    {
    }

    /**
     * Test case for getFilesListForSubpathOfBuildType
     *
     * List files under this path..
     *
     */
    public function testGetFilesListForSubpathOfBuildType()
    {
    }

    /**
     * Test case for getFilesListOfBuildType
     *
     * List all files..
     *
     */
    public function testGetFilesListOfBuildType()
    {
    }

    /**
     * Test case for getSnapshotDependency
     *
     * Get a snapshot dependency of the matching build configuration..
     *
     */
    public function testGetSnapshotDependency()
    {
    }

    /**
     * Test case for getTrigger
     *
     * Get a trigger of the matching build configuration..
     *
     */
    public function testGetTrigger()
    {
    }

    /**
     * Test case for getTriggerParameter
     *
     * Get a parameter of a trigger of the matching build configuration..
     *
     */
    public function testGetTriggerParameter()
    {
    }

    /**
     * Test case for getVcsRoot
     *
     * Get a VCS root of the matching build configuration..
     *
     */
    public function testGetVcsRoot()
    {
    }

    /**
     * Test case for getVcsRootCheckoutRules
     *
     * Get checkout rules of a VCS root of the matching build configuration..
     *
     */
    public function testGetVcsRootCheckoutRules()
    {
    }

    /**
     * Test case for getVcsRootInstancesOfBuildType
     *
     * Get all VCS root instances of the matching build configuration..
     *
     */
    public function testGetVcsRootInstancesOfBuildType()
    {
    }

    /**
     * Test case for getZippedFileOfBuildType
     *
     * Get specific file zipped..
     *
     */
    public function testGetZippedFileOfBuildType()
    {
    }

    /**
     * Test case for removeAllTemplates
     *
     * Detach all templates from the matching build configuration..
     *
     */
    public function testRemoveAllTemplates()
    {
    }

    /**
     * Test case for removeTemplate
     *
     * Detach a template from the matching build configuration..
     *
     */
    public function testRemoveTemplate()
    {
    }

    /**
     * Test case for replaceAgentRequirement
     *
     * Update an agent requirement of the matching build configuration..
     *
     */
    public function testReplaceAgentRequirement()
    {
    }

    /**
     * Test case for replaceAllAgentRequirements
     *
     * Update all agent requirements of the matching build configuration..
     *
     */
    public function testReplaceAllAgentRequirements()
    {
    }

    /**
     * Test case for replaceAllArtifactDependencies
     *
     * Update all artifact dependencies of the matching build configuration..
     *
     */
    public function testReplaceAllArtifactDependencies()
    {
    }

    /**
     * Test case for replaceAllBuildFeatures
     *
     * Update all build features of the matching build configuration..
     *
     */
    public function testReplaceAllBuildFeatures()
    {
    }

    /**
     * Test case for replaceAllBuildSteps
     *
     * Update all build steps of the matching build configuration..
     *
     */
    public function testReplaceAllBuildSteps()
    {
    }

    /**
     * Test case for replaceAllSnapshotDependencies
     *
     * Update all snapshot dependencies of the matching build configuration..
     *
     */
    public function testReplaceAllSnapshotDependencies()
    {
    }

    /**
     * Test case for replaceAllTriggers
     *
     * Update all triggers of the matching build configuration..
     *
     */
    public function testReplaceAllTriggers()
    {
    }

    /**
     * Test case for replaceAllVcsRoots
     *
     * Update all VCS roots of the matching build configuration..
     *
     */
    public function testReplaceAllVcsRoots()
    {
    }

    /**
     * Test case for replaceArtifactDependency
     *
     * Update an artifact dependency of the matching build configuration..
     *
     */
    public function testReplaceArtifactDependency()
    {
    }

    /**
     * Test case for replaceBuildFeature
     *
     * Update a build feature of the matching build configuration..
     *
     */
    public function testReplaceBuildFeature()
    {
    }

    /**
     * Test case for replaceBuildFeatureParameters
     *
     * Update a parameter of a build feature of the matching build configuration..
     *
     */
    public function testReplaceBuildFeatureParameters()
    {
    }

    /**
     * Test case for replaceBuildStep
     *
     * Replace a build step of the matching build configuration..
     *
     */
    public function testReplaceBuildStep()
    {
    }

    /**
     * Test case for replaceSnapshotDependency
     *
     * Update a snapshot dependency of the matching build configuration..
     *
     */
    public function testReplaceSnapshotDependency()
    {
    }

    /**
     * Test case for replaceTrigger
     *
     * Update a trigger of the matching build configuration..
     *
     */
    public function testReplaceTrigger()
    {
    }

    /**
     * Test case for setAgentRequirementParameter
     *
     * Update a parameter of an agent requirement of the matching build configuration..
     *
     */
    public function testSetAgentRequirementParameter()
    {
    }

    /**
     * Test case for setArtifactDependencyParameter
     *
     * Update a parameter of an artifact dependency of the matching build configuration..
     *
     */
    public function testSetArtifactDependencyParameter()
    {
    }

    /**
     * Test case for setBuildFeatureParameter
     *
     * Update a parameter of a build feature of the matching build configuration..
     *
     */
    public function testSetBuildFeatureParameter()
    {
    }

    /**
     * Test case for setBuildStepParameter
     *
     * Update a parameter of a build step of the matching build configuration..
     *
     */
    public function testSetBuildStepParameter()
    {
    }

    /**
     * Test case for setBuildTypeField
     *
     * Update a field of the matching build configuration..
     *
     */
    public function testSetBuildTypeField()
    {
    }

    /**
     * Test case for setBuildTypeTemplates
     *
     * Update all templates of the matching build configuration..
     *
     */
    public function testSetBuildTypeTemplates()
    {
    }

    /**
     * Test case for setTriggerParameter
     *
     * Update a parameter of a trigger of the matching build configuration..
     *
     */
    public function testSetTriggerParameter()
    {
    }

    /**
     * Test case for updateBuildParameterOfBuildType
     *
     * Update build parameter..
     *
     */
    public function testUpdateBuildParameterOfBuildType()
    {
    }

    /**
     * Test case for updateBuildParameterSpecificationOfBuildType
     *
     * Update build parameter specification..
     *
     */
    public function testUpdateBuildParameterSpecificationOfBuildType()
    {
    }

    /**
     * Test case for updateBuildParameterTypeOfBuildType
     *
     * Update type of build parameter..
     *
     */
    public function testUpdateBuildParameterTypeOfBuildType()
    {
    }

    /**
     * Test case for updateBuildParameterValueOfBuildType
     *
     * Update value of build parameter..
     *
     */
    public function testUpdateBuildParameterValueOfBuildType()
    {
    }

    /**
     * Test case for updateBuildParametersOfBuildType
     *
     * Update build parameters..
     *
     */
    public function testUpdateBuildParametersOfBuildType()
    {
    }

    /**
     * Test case for updateBuildTypeVcsRoot
     *
     * Update a VCS root of the matching build configuration..
     *
     */
    public function testUpdateBuildTypeVcsRoot()
    {
    }

    /**
     * Test case for updateBuildTypeVcsRootCheckoutRules
     *
     * Update checkout rules of a VCS root of the matching build configuration..
     *
     */
    public function testUpdateBuildTypeVcsRootCheckoutRules()
    {
    }
}
