<?php
/**
 * ChangeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AceViral\TeamCity;

use \AceViral\TeamCity\Configuration;
use \AceViral\TeamCity\ApiException;
use \AceViral\TeamCity\ObjectSerializer;

/**
 * ChangeApiTest Class Doc Comment
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAllChanges
     *
     * Get all changes..
     *
     */
    public function testGetAllChanges()
    {
    }

    /**
     * Test case for getChange
     *
     * Get change matching the locator..
     *
     */
    public function testGetChange()
    {
    }

    /**
     * Test case for getChangeAttributes
     *
     * Get attributes of the matching change..
     *
     */
    public function testGetChangeAttributes()
    {
    }

    /**
     * Test case for getChangeDuplicates
     *
     * Get duplicates of the matching change..
     *
     */
    public function testGetChangeDuplicates()
    {
    }

    /**
     * Test case for getChangeField
     *
     * Get a field of the matching change..
     *
     */
    public function testGetChangeField()
    {
    }

    /**
     * Test case for getChangeFirstBuilds
     *
     * Get first builds of the matching change..
     *
     */
    public function testGetChangeFirstBuilds()
    {
    }

    /**
     * Test case for getChangeIssue
     *
     * Get issues of the matching change..
     *
     */
    public function testGetChangeIssue()
    {
    }

    /**
     * Test case for getChangeParentChanges
     *
     * Get parent changes of the matching change..
     *
     */
    public function testGetChangeParentChanges()
    {
    }

    /**
     * Test case for getChangeParentRevisions
     *
     * Get parent revisions of the matching change..
     *
     */
    public function testGetChangeParentRevisions()
    {
    }

    /**
     * Test case for getChangeRelatedBuildTypes
     *
     * Get build configurations related to the matching change..
     *
     */
    public function testGetChangeRelatedBuildTypes()
    {
    }

    /**
     * Test case for getChangeVcsRoot
     *
     * Get a VCS root instance of the matching change..
     *
     */
    public function testGetChangeVcsRoot()
    {
    }

    /**
     * Test case for getUniqueCommiters
     *
     * Get unique commiters of the matching changes..
     *
     */
    public function testGetUniqueCommiters()
    {
    }
}
