<?php
/**
 * CloudInstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AceViral\TeamCity;

use \AceViral\TeamCity\Configuration;
use \AceViral\TeamCity\ApiException;
use \AceViral\TeamCity\ObjectSerializer;

/**
 * CloudInstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CloudInstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAllCloudImages
     *
     * Get all cloud images..
     *
     */
    public function testGetAllCloudImages()
    {
    }

    /**
     * Test case for getAllCloudInstances
     *
     * Get all cloud instances..
     *
     */
    public function testGetAllCloudInstances()
    {
    }

    /**
     * Test case for getAllCloudProfiles
     *
     * Get all cloud profiles..
     *
     */
    public function testGetAllCloudProfiles()
    {
    }

    /**
     * Test case for getCloudImage
     *
     * Get cloud image matching the locator..
     *
     */
    public function testGetCloudImage()
    {
    }

    /**
     * Test case for getCloudInstance
     *
     * Get cloud instance matching the locator..
     *
     */
    public function testGetCloudInstance()
    {
    }

    /**
     * Test case for getCloudProfile
     *
     * Get cloud profile matching the locator..
     *
     */
    public function testGetCloudProfile()
    {
    }

    /**
     * Test case for startInstance
     *
     * Start a new cloud instance..
     *
     */
    public function testStartInstance()
    {
    }

    /**
     * Test case for stopInstance
     *
     * Stop cloud instance matching the locator..
     *
     */
    public function testStopInstance()
    {
    }
}
