<?php
/**
 * InvestigationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InvestigationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvestigationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addInvestigation
     *
     * Create a new investigation..
     *
     */
    public function testAddInvestigation()
    {
    }

    /**
     * Test case for addMultipleInvestigations
     *
     * Create multiple new investigations..
     *
     */
    public function testAddMultipleInvestigations()
    {
    }

    /**
     * Test case for deleteInvestigation
     *
     * Delete investigation matching the locator..
     *
     */
    public function testDeleteInvestigation()
    {
    }

    /**
     * Test case for getAllInvestigations
     *
     * Get all investigations..
     *
     */
    public function testGetAllInvestigations()
    {
    }

    /**
     * Test case for getInvestigation
     *
     * Get investigation matching the locator..
     *
     */
    public function testGetInvestigation()
    {
    }

    /**
     * Test case for replaceInvestigation
     *
     * Update investigation matching the locator..
     *
     */
    public function testReplaceInvestigation()
    {
    }
}
