<?php
/**
 * ProjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AceViral\TeamCity;

use \AceViral\TeamCity\Configuration;
use \AceViral\TeamCity\ApiException;
use \AceViral\TeamCity\ObjectSerializer;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  AceViral\TeamCity
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addAgentPoolsProject
     *
     * Assign the matching project to the agent pool..
     *
     */
    public function testAddAgentPoolsProject()
    {
    }

    /**
     * Test case for addBuildType
     *
     * Add a build configuration to the matching project..
     *
     */
    public function testAddBuildType()
    {
    }

    /**
     * Test case for addFeature
     *
     * Add a feature..
     *
     */
    public function testAddFeature()
    {
    }

    /**
     * Test case for addProject
     *
     * Create a new project..
     *
     */
    public function testAddProject()
    {
    }

    /**
     * Test case for addSecureToken
     *
     * Create a new secure token for the matching project..
     *
     */
    public function testAddSecureToken()
    {
    }

    /**
     * Test case for addTemplate
     *
     * Add a build configuration template to the matching project..
     *
     */
    public function testAddTemplate()
    {
    }

    /**
     * Test case for createBuildParameter
     *
     * Create a build parameter..
     *
     */
    public function testCreateBuildParameter()
    {
    }

    /**
     * Test case for deleteBuildParameter
     *
     * Delete build parameter..
     *
     */
    public function testDeleteBuildParameter()
    {
    }

    /**
     * Test case for deleteBuildParameters
     *
     * Delete all build parameters..
     *
     */
    public function testDeleteBuildParameters()
    {
    }

    /**
     * Test case for deleteFeature
     *
     * Delete a matching feature..
     *
     */
    public function testDeleteFeature()
    {
    }

    /**
     * Test case for deleteProject
     *
     * Delete project matching the locator..
     *
     */
    public function testDeleteProject()
    {
    }

    /**
     * Test case for getAgentPoolsProject
     *
     * Get agent pools appointed to the matching project..
     *
     */
    public function testGetAgentPoolsProject()
    {
    }

    /**
     * Test case for getAllBranches
     *
     * Get all branches of the matching project..
     *
     */
    public function testGetAllBranches()
    {
    }

    /**
     * Test case for getAllProjects
     *
     * Get all projects..
     *
     */
    public function testGetAllProjects()
    {
    }

    /**
     * Test case for getAllSubprojectsOrdered
     *
     * Get all subprojects ordered of the matching project..
     *
     */
    public function testGetAllSubprojectsOrdered()
    {
    }

    /**
     * Test case for getBuildParameter
     *
     * Get build parameter..
     *
     */
    public function testGetBuildParameter()
    {
    }

    /**
     * Test case for getBuildParameterSpecification
     *
     * Get build parameter specification..
     *
     */
    public function testGetBuildParameterSpecification()
    {
    }

    /**
     * Test case for getBuildParameterType
     *
     * Get type of build parameter..
     *
     */
    public function testGetBuildParameterType()
    {
    }

    /**
     * Test case for getBuildParameterValue
     *
     * Get value of build parameter..
     *
     */
    public function testGetBuildParameterValue()
    {
    }

    /**
     * Test case for getBuildParameters
     *
     * Get build parameters..
     *
     */
    public function testGetBuildParameters()
    {
    }

    /**
     * Test case for getDefaultTemplate
     *
     * Get the default template of the matching project..
     *
     */
    public function testGetDefaultTemplate()
    {
    }

    /**
     * Test case for getFeature
     *
     * Get a matching feature..
     *
     */
    public function testGetFeature()
    {
    }

    /**
     * Test case for getFeatures
     *
     * Get all features..
     *
     */
    public function testGetFeatures()
    {
    }

    /**
     * Test case for getProject
     *
     * Get project matching the locator..
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for getProjectField
     *
     * Get a field of the matching project..
     *
     */
    public function testGetProjectField()
    {
    }

    /**
     * Test case for getProjectParentProject
     *
     * Get the parent project of the matching project..
     *
     */
    public function testGetProjectParentProject()
    {
    }

    /**
     * Test case for getProjectSettingsFile
     *
     * Get the settings file of the matching build configuration..
     *
     */
    public function testGetProjectSettingsFile()
    {
    }

    /**
     * Test case for getProjectTemplates
     *
     * Get all templates of the matching project..
     *
     */
    public function testGetProjectTemplates()
    {
    }

    /**
     * Test case for getSecureValue
     *
     * Get a secure token of the matching project..
     *
     */
    public function testGetSecureValue()
    {
    }

    /**
     * Test case for removeDefaultTemplate
     *
     * Remove the default template from the matching project..
     *
     */
    public function testRemoveDefaultTemplate()
    {
    }

    /**
     * Test case for removeProjectFromAgentPool
     *
     * Unassign a project from the matching agent pool..
     *
     */
    public function testRemoveProjectFromAgentPool()
    {
    }

    /**
     * Test case for setAgentPoolsProject
     *
     * Update agent pools apppointed to the matching project..
     *
     */
    public function testSetAgentPoolsProject()
    {
    }

    /**
     * Test case for setBuildTypesOrder
     *
     * Update all build configurations order of the matching project..
     *
     */
    public function testSetBuildTypesOrder()
    {
    }

    /**
     * Test case for setDefaultTemplate
     *
     * Update the default template of the matching project..
     *
     */
    public function testSetDefaultTemplate()
    {
    }

    /**
     * Test case for setParentProject
     *
     * Update the parent project of the matching project..
     *
     */
    public function testSetParentProject()
    {
    }

    /**
     * Test case for setProjectField
     *
     * Update a field of the matching project..
     *
     */
    public function testSetProjectField()
    {
    }

    /**
     * Test case for setSubprojectsOrder
     *
     * Update all subprojects order of the matching project..
     *
     */
    public function testSetSubprojectsOrder()
    {
    }

    /**
     * Test case for updateBuildParameter
     *
     * Update build parameter..
     *
     */
    public function testUpdateBuildParameter()
    {
    }

    /**
     * Test case for updateBuildParameterSpecification
     *
     * Update build parameter specification..
     *
     */
    public function testUpdateBuildParameterSpecification()
    {
    }

    /**
     * Test case for updateBuildParameterType
     *
     * Update type of build parameter..
     *
     */
    public function testUpdateBuildParameterType()
    {
    }

    /**
     * Test case for updateBuildParameterValue
     *
     * Update value of build parameter..
     *
     */
    public function testUpdateBuildParameterValue()
    {
    }

    /**
     * Test case for updateBuildParameters
     *
     * Update build parameters..
     *
     */
    public function testUpdateBuildParameters()
    {
    }

    /**
     * Test case for updateFeature
     *
     * Update a matching feature..
     *
     */
    public function testUpdateFeature()
    {
    }

    /**
     * Test case for updateFeatures
     *
     * Update all features..
     *
     */
    public function testUpdateFeatures()
    {
    }
}
