<?php
/**
 * ServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLicenseKeys
     *
     * Add license keys..
     *
     */
    public function testAddLicenseKeys()
    {
    }

    /**
     * Test case for deleteLicenseKey
     *
     * Delete a license key..
     *
     */
    public function testDeleteLicenseKey()
    {
    }

    /**
     * Test case for downloadFileOfServer
     *
     * Download specific file..
     *
     */
    public function testDownloadFileOfServer()
    {
    }

    /**
     * Test case for getAllMetrics
     *
     * Get metrics..
     *
     */
    public function testGetAllMetrics()
    {
    }

    /**
     * Test case for getAllPlugins
     *
     * Get all plugins..
     *
     */
    public function testGetAllPlugins()
    {
    }

    /**
     * Test case for getBackupStatus
     *
     * Get the latest backup status..
     *
     */
    public function testGetBackupStatus()
    {
    }

    /**
     * Test case for getFileMetadataOfServer
     *
     * Get metadata of specific file..
     *
     */
    public function testGetFileMetadataOfServer()
    {
    }

    /**
     * Test case for getFilesListForSubpathOfServer
     *
     * List files under this path..
     *
     */
    public function testGetFilesListForSubpathOfServer()
    {
    }

    /**
     * Test case for getFilesListOfServer
     *
     * List all files..
     *
     */
    public function testGetFilesListOfServer()
    {
    }

    /**
     * Test case for getLicenseKey
     *
     * Get a license key..
     *
     */
    public function testGetLicenseKey()
    {
    }

    /**
     * Test case for getLicenseKeys
     *
     * Get all license keys..
     *
     */
    public function testGetLicenseKeys()
    {
    }

    /**
     * Test case for getLicensingData
     *
     * Get the licensing data..
     *
     */
    public function testGetLicensingData()
    {
    }

    /**
     * Test case for getServerField
     *
     * Get a field of the server info..
     *
     */
    public function testGetServerField()
    {
    }

    /**
     * Test case for getServerInfo
     *
     * Get the server info..
     *
     */
    public function testGetServerInfo()
    {
    }

    /**
     * Test case for getZippedFileOfServer
     *
     * Get specific file zipped..
     *
     */
    public function testGetZippedFileOfServer()
    {
    }

    /**
     * Test case for startBackup
     *
     * Start a new backup..
     *
     */
    public function testStartBackup()
    {
    }
}
